### PR TITLE
Add "uninstall" and "remove" target

### PR DESCRIPTION
**Pull request by mkg20001**

### CODE REVIEW

**Comment by whyrusleeping** [comment]
why both remove and uninstall?

**Comment by mkg20001** [comment]
If someone uses remove instead of uninstall...

**Comment by whyrusleeping** [comment]
lets just stick with uninstall. By that logic we should add "get-rid-of", "delete" and "cleanup"

**Comment by mkg20001** [comment]
Ok,

**Comment by whyrusleeping** [comment]
Cool, thanks!

**Comment by mkg20001** [comment]
No problem

**Pull request merged**
